use crate::parser::Program;
use std::fs;
use std::io;
use std::process::{Command, Stdio};

#[derive(Debug)]
pub enum CompileError {
    Parse(String),
    Io(String),
    Compilation(String),
    NoCompiler,
}

pub struct Compiler;

impl Compiler {
    fn generate_c_code(&self, program: &Program) -> String {
        let mut c_code = String::new();
        
        c_code.push_str("/* Generated by Quark Compiler */\n");
        c_code.push_str("#include <stdio.h>\n");
        c_code.push_str("#include <stdlib.h>\n\n");
        c_code.push_str("int main() {\n");
        
        for statement in &program.statements {
            match statement {
                crate::parser::Expr::Call { name, args } if name == "echo" => {
                    if let Some(arg) = args.first() {
                        let escaped_arg = arg
                            .replace('\\', "\\\\")
                            .replace('\"', "\\\"")
                            .replace('\n', "\\n")
                            .replace('\t', "\\t")
                            .replace('\r', "\\r")
                            .replace('%', "%%");
                        
                        c_code.push_str(&format!("    printf(\"{}\\n\");\n", escaped_arg));
                    }
                }
                _ => {}
            }
        }
        
        c_code.push_str("    return 0;\n");
        c_code.push_str("}\n");
        
        c_code
    }

    fn try_compiler(&self, compiler: &str, args: &[&str]) -> Result<(), CompileError> {
        let output = Command::new(compiler)
            .args(args)
            .stdout(Stdio::null())
            .stderr(Stdio::piped())
            .output()
            .map_err(|e| CompileError::Io(e.to_string()))?;
        
        if output.status.success() {
            Ok(())
        } else {
            let stderr = String::from_utf8_lossy(&output.stderr);
            Err(CompileError::Compilation(format!("{}: {}", compiler, stderr)))
        }
    }

    fn detect_c_compiler(&self) -> Result<&'static str, CompileError> {
        let compilers = if cfg!(target_os = "windows") {
            ["gcc", "clang", "cl"]
        } else {
            ["gcc", "clang", "cc"]
        };

        for &compiler in &compilers {
            if self.try_compiler(compiler, &["--version"]).is_ok() {
                return Ok(compiler);
            }
        }

        Err(CompileError::NoCompiler)
    }

    pub fn compile_to_exe(&self, program: &Program, output_path: &str) -> Result<(), CompileError> {
        let c_code = self.generate_c_code(program);
        let c_file = "quark_temp.c";
        
        fs::write(c_file, &c_code)
            .map_err(|e| CompileError::Io(e.to_string()))?;

        let compiler = self.detect_c_compiler()?;

        let args: Vec<&str> = match compiler {
            "cl" => vec![c_file, "/Fe:", output_path, "/nologo", "/O2"],
            _ => vec![c_file, "-o", output_path, "-O2", "-s"],
        };

        self.try_compiler(compiler, &args)?;

        let _ = fs::remove_file(c_file);
        
        Ok(())
    }
}